apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: axcvm7hn2-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/axcvm7hn2-dotnet-basic-gitops